# Generated by Django 5.2.17 on 2026-09-10 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('support_level', models.CharField(choices=[('full', 'Fully supported'), ('starter', 'Starter guidance')], default='full', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'career_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gaps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictions.predictionrun')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_snapshots', to='careers.careerrole')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_snapshots', to='students.studentprofile')),
            ],
            options={
                'db_table': 'skill_gap_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleSkillBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('rationale', models.CharField(blank=True, max_length=300)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='careers.careerrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_benchmarks', to='students.skill')),
            ],
            options={
                'db_table': 'role_skill_benchmarks',
                'constraints': [models.UniqueConstraint(fields=('role', 'skill'), name='unique_role_skill_benchmark')],
            },
        ),
        migrations.CreateModel(
            name='StudentRoleSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_selections', to='careers.careerrole')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_selections', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_role_selections',
                'constraints': [models.UniqueConstraint(fields=('student', 'role'), name='unique_student_role_selection')],
            },
        ),
    ]
