# Generated by Django 5.2.17 on 2026-09-10 19:13

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('diagnostic', 'Diagnostic Assessment'), ('practice', 'Practice Test'), ('mock_interview', 'Mock Interview'), ('proctored', 'Proctored Assessment')], db_index=True, default='diagnostic', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('evaluated', 'Evaluated')], default='completed', max_length=30)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('quantitative', 'Quantitative Aptitude'), ('logical', 'Logical Reasoning'), ('coding', 'Coding & Problem Solving'), ('communication', 'Communication Skills'), ('interview', 'Technical Interview'), ('presentation', 'Presentation Skills')], db_index=True, max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))])),
            ],
            options={
                'db_table': 'assessment_scores',
            },
        ),
    ]
