# Generated by Django 5.2.17 on 2026-09-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['assessment', 'dimension'], name='assessment__assessm_008a63_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.UniqueConstraint(fields=('assessment', 'dimension'), name='unique_assessment_dimension_score'),
        ),
    ]
