# Generated by Django 5.2.17 on 2026-09-10 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_gap_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.skillgapsnapshot')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.careerrole')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='students.studentprofile')),
            ],
            options={
                'db_table': 'roadmaps',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='roadmaps.roadmap')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.skill')),
            ],
            options={
                'db_table': 'roadmap_items',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('roadmap', 'sequence'), name='unique_roadmap_sequence')],
            },
        ),
    ]
