import { FormEvent, useState, type ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/app/AuthContext";
import { errorMessage } from "@/lib/api";
import { Button } from "@/components/ui/button";

const input = "w-full rounded-md border bg-white px-3 py-2 text-sm";
export function LoginPage() { const auth = useAuth(), navigate = useNavigate(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { const user = await auth.signIn(String(data.get("email")), String(data.get("password"))); navigate(user.role === "student" ? "/student" : "/tpo"); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <AuthCard title="Welcome back" footer={<Link className="text-indigo-600" to="/register">Create a student account</Link>}><form onSubmit={submit} className="space-y-3"><input className={input} name="email" type="email" placeholder="Email" required /><input className={input} name="password" type="password" placeholder="Password" required />{error && <Error text={error} />}<Button disabled={busy} className="w-full">{busy ? "Signing in…" : "Sign in"}</Button></form></AuthCard>; }
export function RegisterPage() { const auth = useAuth(), navigate = useNavigate(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; try { await auth.register(data); const user = await auth.signIn(data.email, data.password); navigate(user.role === "student" ? "/student" : "/tpo"); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <AuthCard title="Create student account" footer={<Link className="text-indigo-600" to="/login">Already have an account?</Link>}><form onSubmit={submit} className="space-y-3"><input className={input} name="first_name" placeholder="First name" /><input className={input} name="last_name" placeholder="Last name" /><input className={input} name="email" type="email" placeholder="Email" required /><input className={input} name="password" type="password" minLength={8} placeholder="Password (8+ characters)" required />{error && <Error text={error} />}<Button disabled={busy} className="w-full">{busy ? "Creating…" : "Create account"}</Button></form></AuthCard>; }
function AuthCard({ title, children, footer }: { title: string; children: ReactNode; footer: ReactNode }) { return <section className="mx-auto max-w-md rounded-xl border bg-white p-6 shadow-sm"><p className="text-sm font-medium text-indigo-600">EmployIQ</p><h1 className="mt-1 text-2xl font-bold">{title}</h1><div className="mt-6">{children}</div><p className="mt-5 text-center text-sm text-slate-600">{footer}</p></section>; }
export function Error({ text }: { text: string }) { return <p role="alert" className="rounded bg-rose-50 p-2 text-sm text-rose-700">{text}</p>; }
