import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { api, errorMessage } from "@/lib/api";
import type { TpoOverview } from "@/lib/types";

const get = <T,>(path: string) => async () => (await api.get<T>(path)).data;
export function TpoPage() { const overview = useQuery({ queryKey: ["tpo-overview"], queryFn: get<TpoOverview>("/v1/analytics/overview/") }); const interventions = useQuery({ queryKey: ["tpo-interventions"], queryFn: get<{ results: { student_name: string; email: string; probability_percent: number; readiness: string }[] }>("/v1/analytics/interventions/") }); const departments = useQuery({ queryKey: ["tpo-departments"], queryFn: get<{ results: { department: string; students_with_predictions: number; average_probability_percent: number; below_60_count: number }[] }>("/v1/analytics/departments/") }); const skills = useQuery({ queryKey: ["tpo-skills"], queryFn: get<{ results: { skill: string; students_with_gap: number }[] }>("/v1/analytics/skills/") });
  if (overview.isLoading) return <p>Loading institutional analytics…</p>; if (overview.isError) return <p role="alert">{errorMessage(overview.error)}</p>; const data = overview.data!;
  return <section className="space-y-6"><div><p className="text-sm font-medium text-indigo-600">TPO workspace</p><h1 className="text-3xl font-bold">Institution readiness</h1></div><div className="grid gap-3 sm:grid-cols-3"><Stat label="Students" value={data.total_students} /><Stat label="Predictions" value={data.students_with_predictions} /><Stat label="Average readiness" value={`${data.average_probability_percent}%`} /></div><Panel title="Readiness distribution"><pre className="text-sm">{JSON.stringify(data.readiness_breakdown, null, 2)}</pre></Panel><Panel title="Department readiness">{departments.data?.results.length ? <table className="w-full text-left text-sm"><thead><tr><th>Department</th><th>Predictions</th><th>Average</th><th>Below 60%</th></tr></thead><tbody>{departments.data.results.map(item => <tr key={item.department}><td>{item.department}</td><td>{item.students_with_predictions}</td><td>{item.average_probability_percent}%</td><td>{item.below_60_count}</td></tr>)}</tbody></table> : <p>No department prediction data yet.</p>}</Panel><Panel title="Students below 60%">{interventions.data?.results.length ? interventions.data.results.map(item => <p key={item.email}>{item.student_name || item.email} — {item.probability_percent}% ({item.readiness})</p>) : <p>No intervention students yet.</p>}</Panel><Panel title="Institutional skill deficits">{skills.data?.results.length ? skills.data.results.map(item => <p key={item.skill}>{item.skill}: {item.students_with_gap} students</p>) : <p>No gap data yet.</p>}</Panel></section>; }
export function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-lg border bg-white p-4"><h2 className="mb-3 font-semibold">{title}</h2>{children}</section>; }
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-bold">{value}</p></div>; }
