# Generated by Django 5.2.17 on 2026-09-10 19:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming_language', 'Programming Language'), ('framework', 'Framework / Library'), ('database', 'Database'), ('cloud_devops', 'Cloud & DevOps'), ('core_cs', 'Core CS (DSA, OS, DBMS, Networks)'), ('soft_skill', 'Soft Skill / Communication')], db_index=True, default='programming_language', max_length=50)),
                ('canonical_key', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('tenth_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('current_backlogs', models.PositiveIntegerField(default=0)),
                ('history_of_backlogs', models.PositiveIntegerField(default=0)),
                ('aptitude_score', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('communication_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('extracurricular_score', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='accounts.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('project', 'Project'), ('internship', 'Internship'), ('open_source', 'Open Source'), ('research', 'Research')], default='project', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_experiences',
            },
        ),
        migrations.CreateModel(
            name='StudentCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('earned_at', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_certifications',
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('source', models.CharField(choices=[('self_reported', 'Self Reported'), ('assessment', 'Assessment Verified'), ('coursework', 'Coursework')], default='self_reported', max_length=30)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_skills', to='students.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_skills',
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['institution', 'cohort', 'department'], name='student_pro_institu_154e08_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentskill',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='unique_student_skill'),
        ),
    ]
